// 按需全局引入 vant组件
import Vue from 'vue'
import { Button, List, Cell, Tabbar, TabbarItem, Tab, Tabs, NavBar, Skeleton, Image, CellGroup, Field, Picker, Popup, Area, Row, GoodsAction, GoodsActionButton, Progress, Swipe, SwipeItem, Lazyload, Toast, Divider, Dialog, Checkbox } from 'vant'
Vue.use(Button)
Vue.use(Cell)
Vue.use(List)
Vue.use(NavBar)
Vue.use(Tab).use(Tabs)
Vue.use(Tabbar).use(TabbarItem)
Vue.use(Skeleton)
Vue.use(Image)
Vue.use(CellGroup).use(Field)
Vue.use(Picker)
Vue.use(Popup)
Vue.use(Area)
Vue.use(Row)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(Progress)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Lazyload)
Vue.use(Toast)
Vue.use(Divider)
Vue.use(Dialog)
Vue.use(Checkbox)
